# This workflow will build Jira Assistant plugin and publish to Jira Cloud staging environment by default

name: Deploy Jira Cloud App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment to publish'
        default: 'staging'
        required: true
        type: choice
        options:
        - development
        - staging
        - production
      jiraSiteUrl:
        description: 'Jira cloud host name'
        default: 'jira-ja.atlassian.net'
        required: true
        type: string
      forgeEmail:
        description: 'Atlassian Email id'
        required: true
        type: string
      forgeApiToken:
        description: 'Atlassian API token'
        required: true
        type: string
  push:
    branches: [ package, master ]
  pull_request:
    branches: [ package, master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: ""
      JIRA_SITE_URL: jira-ja.atlassian.net
      FORGE_ENV: staging
      FORGE_EMAIL: ${{ secrets.FORGE_LOGIN_ID }}
      FORGE_API_TOKEN: ${{ secrets.FORGE_LOGIN_PWD }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Set env based on branch
      run: |
        echo "FORGE_ENV=production" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/heads/master')
      
    - name: Override env with user inputs
      run: |
        echo "FORGE_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
        echo "JIRA_SITE_URL=${{ github.event.inputs.jiraSiteUrl }}" >> $GITHUB_ENV
        echo "FORGE_EMAIL=${{ github.event.inputs.forgeEmail }}" >> $GITHUB_ENV
        echo "FORGE_API_TOKEN=${{ github.event.inputs.forgeApiToken }}" >> $GITHUB_ENV
      if: startsWith(github.event_name, 'workflow_dispatch')
      
    - run: echo Deploying ${{github.ref}} to ${{env.FORGE_ENV}} of ${{env.JIRA_SITE_URL}}
    - run: npm install -g @forge/cli@latest
    - run: npm install --force
    - run: npm run build-plugin
    - run: forge settings set usage-analytics false
    - run: forge deploy -e $FORGE_ENV
    - run: forge install -e $FORGE_ENV -s $JIRA_SITE_URL -p Jira --upgrade --confirm-scopes --non-interactive
    - run: forge logout
